config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  namespace :customers do
    get "/index" , action: "index"
    get "/register" , action: "new"
    post "/" , action: "create"
    get "/personal/:id" , action: "show"
    get "/activated/:id" , action: "activated"
    get "/login_form" , action: "login_form"
    post "/login" , action: "login"
    post "/logout" , action: "logout"
  end

  namespace :product_packages do
    get "/index" , action: "index"
    post "/order_type", action: "order_type"
    get "/order_detail_form", action: "order_detail_form"
    post "/order_detail", action: "order_detail"
  end

  namespace :orders do
    get "/index" , action: "index"
    get "/:id/confirm_form", action: "confirm_form"
    post "/:id/confirm", action: "confirm"
    get "/:id/payment", action: "payment"
    get "/payment/:id/success", action: "payment_success"
    get "/payment/:id/fail", action: "payment_fail"
    get "/reset", action: "reset"
  end

  namespace :employees do
    get "/index" , action: "index"
    get "/create_package_form" , action: "create_package_form"
    post "/create_package", action: "create_package"
    get "/create_optional_form" , action: "create_optional_form"
    post "/create_optional", action: "create_optional"
    get "/statistics" , action: "statistics"
  end


  get '/' => "home#index"
  get 'optional_products/index'
  get 'alerts/index'
  get 'products/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/alert.rb
class Alert < ApplicationRecord
  belongs_to :customer
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
    has_many :service_activation_schedule
    has_many :orders, through: :service_activation_schedule
end

app/models/employee.rb
class Employee < ApplicationRecord
end

app/models/optional_product.rb
class OptionalProduct < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :product_package
  belongs_to :customer
  belongs_to :validity_period
  has_many :optional_product_orders
  has_many :optional_products, through: :optional_product_orders
end

app/models/package_optional.rb
class PackageOptional < ApplicationRecord
  belongs_to :product_package
  belongs_to :optional_product
end

app/models/package_validity.rb
class PackageValidity < ApplicationRecord
  belongs_to :product_package
  belongs_to :validity_period
end

app/models/price.rb
class Price < ApplicationRecord
  belongs_to :validity_period
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/product_package.rb
class ProductPackage < ApplicationRecord
    has_many :product_composition
    has_many :products, through: :product_composition
    has_many :package_validity
    has_many :validity_periods, through: :package_validity
    has_many :package_optional
    has_many :optional_products, through: :package_optional
end

app/models/product_type.rb
class ProductType < ApplicationRecord
end

app/models/validity_period.rb
class ValidityPeriod < ApplicationRecord
end

app/helpers/alerts_helper.rb
module AlertsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EmployeeServiceLite</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <nav class="navbar">
      `<ul>
          <li><%= link_to("Telcom","/")%></li>
          <% if @name != "Employee" && @name != "Login"%>
          <li><%= link_to("Purchased list","/customers/activated/#{@current_user.id}")%></li>
          <% elsif @name == "Employee"%>
          <li><%= link_to("Package Creation","/employees/create_package_form")%></li>
          <li><%= link_to("Optional Product Creation","/employees/create_optional_form")%></li>
          <li><%= link_to("Sales Report","/employees/statistics")%></li>
          <%end%>
          <li><%= link_to("Buy Service","/product_packages/index")%></li>
          <div class="search">
            <% if @name == "Login"%>
            <li><%= link_to("Register","/customers/register")%></li>
            <% elsif @name != "Employee"%>
            <li><%= link_to("#{@name}","/customers/personal/#{@current_user.id}" )%></li>
            &nbsp;&nbsp;
            <li><%= link_to 'Logout', customers_logout_path, method: :post %></li>
            <% else%>
            <li><%= link_to 'Logout', customers_logout_path, method: :post %></li>
            <% end %>
          </div>
      </ul>
  </nav>
`
  <% if flash[:notice]%>
      <div class="flash">
        <%= flash[:notice]%>
      </div>
  <% end %>

  <% if flash[:notice]%>
      <div class="flash">
        <%= flash[:notice]%>
      </div>
  <% end %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>